//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace People_Search
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int userid { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string address { get; set; }
        public Nullable<int> age { get; set; }
        public string interests { get; set; }
        public byte[] pic { get; set; }
    }
}
